def get_navbar_context(request):
    url_name = request.resolver_match.url_name if request.resolver_match else ""
    heading_map = {
        "index": "Dashboard",
        "brand_summary": "Brand",
        "brand_create": "Tambah Brand",
        "brand_update": "Perbarui Brand",
        "ads_list": "Advertisement",
        "ads_create": "Tambah Iklan",
        "ads_update": "Perbarui Iklan",
        "ads_delete": "Hapus Iklan",
        "category_list": "Category",
        "category_create": "Tambah Kategori",
        "category_update": "Perbarui Kategori",
        "category_delete": "Hapus Kategori",
        "tag_list": "Tag",
        "tag_create": "Tambah Tag",
        "tag_update": "Perbarui Tag",
        "tag_delete": "Hapus Tag",
        "page_list": "Page",
        "page_create": "Tambah Halaman",
        "page_update": "Perbarui Halaman",
        "page_delete": "Hapus Halaman",
        "article_list": "Article",
        "article_create": "Tambah Artikel",
        "article_update": "Perbarui Artikel",
        "article_delete": "Hapus Artikel",
        "carousel_list": "Carousel",
        "carousel_create": "Tambah Carousel",
        "carousel_update": "Perbarui Carousel",
        "carousel_delete": "Hapus Carousel",
        "participant_list": "Participant",
        "participant_create": "Tambah Participant",
        "participant_update": "Perbarui Participant",
        "participant_detail": "Detail Participant",
        "participant_delete": "Hapus Participant",
        "account_list": "Account",
        "account_create": "Tambah Account",
        "account_update": "Perbarui Account",
        "account_delete": "Hapus Account",
        "album_list": "Gallery",
        "album_create": "Tambah Album",
        "album_update": "Perbarui Album",
        "album_delete": "Hapus Album",
        "photo_list": "Photos",
        "photo_create": "Tambah Foto",
        "photo_update": "Perbarui Foto",
        "photo_delete": "Hapus Foto",
        "comment_list": "Comments",
        "comment_update": "Ubah Status Komentar",
        "comment_delete": "Hapus Komentar",
        "configuration": "Syncronization",
        "webhook": "Webhook",
    }
    navbar_heading = heading_map.get(url_name, "Dashboard")
    return {
        "navbar_heading": navbar_heading,
    }
