# Generated by Django 5.2.2 on 2026-09-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='type_ads',
        ),
    ]
